import React from "react";
import "./MacBookAir8.css";

function MacBookAir8(props) {
  const { zooplabg, membersTermsAndConditions, overlapGroup1, line31 } = props;

  return (
    <div className="container-center-horizontal">
      <div className="macbook-air-8 screen">
        <div className="overlap-group2-5">
          <img className="zoopla-bg-1" src={zooplabg} alt="ZooplaBG" />
          <div className="overlap-group-8">
            <div className="members-terms-and-conditions inter-bold-black-32px">{membersTermsAndConditions}</div>
          </div>
          <p className="definitions-in-these">
            Definitions
            <br />
            <br /> In these Member Terms and Conditions, the following definitions shall apply:
            <br />
            &#34;Agent&#34; means an estate agent, lettings agent (and in Scotland, solicitor agents) and/or commercial
            property agent;
            <br />
            &#34;Business Day&#34; means any day other than a Saturday, Sunday or public holiday in England, when the
            banks in London are open for business;
            <br />
            &#34;Business Hours&#34; means between the hours of 9:00am to 5:30pm (GMT) on a Business Day;
            <br />
            &#34;Content&#34; means any content and materials made available by, on behalf or on the instruction of, the
            Member to Zoopla or any Group Company on the Website(s), including (without limitation) property details,
            any intellectual property rights, Lead Content, Photograph Content and Video Content;
            <br />
            &#34;Contract&#34; or &#34;Agreement&#34; means a contract for Services between Zoopla and the Member
            governed by these Member Terms and Conditions, the Order Form and, where appropriate, Product Specific Terms
            and Conditions;
            <br />
            &#34;Controller&#34; is defined in the Data Protection Legislation;
            <br />
            &#34;Data Subject&#34; is defined in the Data Protection Legislation;
            <br />
            &#34;Data Subject Rights&#34; means the rights of Data Subjects set out in Chapter III of the GDPR;
            <br />
            &#34;Developer&#34; means a property developer, agencies which act on behalf of a property developer,
            housing associations, companies or agencies which operate within the retirement property market and all
            other agencies, companies and property developers which deal with the marketing of properties (except for
            Agents and Online Agents);
            <br />
            &#34;Development&#34; means a newly built property, or a newly converted building where there has been a
            change of use from something other than residential usage, which carries some form of new build warranty and
            be classed as &#39;new&#39; for mortgage purposes;
            <br />
            &#34;Data Protection Legislation&#34; means the EU General Data Protection Regulation (Regulation (EU)
            2016/679) (&#34;GDPR&#34;) and the Privacy and Electronic Communications Regulations 2003, and (in each
            case) any successor legislation enacted in the United Kingdom;
            <br />
            &#34;Fees&#34; means the amounts due to Zoopla (or any Group Companies) by the Member under the Contract and
            set out or calculated in accordance with the Order Form (as varied from time to time in accordance with
            clause 4.9);
            <br />
            &#34;Force Majeure Event&#34; means an Act of God; war; riot, civil commotion; strike, lockout or other
            labour disturbance (not including those involving the party&#39;s employees); or any other circumstances
            beyond the control of the party seeking to invoke Force Majeure which include outbreak of epidemics and
            infectious diseases such as plagues, quarantine restrictions or restrictions against entry into any country
            where services or materials are being obtained or delivered and which operate to frustrate the Contract;
            <br />
            &#34;Group&#34; means Zoopla and any holding company or companies and any subsidiary undertaking(s) of
            Zoopla or Zoopla&#39;s ultimate parent company from time to time and &#34;Group Company&#34; means any one
            of them;
            <br />
            &#34;Initial Term&#34; means an initial term of the Contract, if any, as set out in the Order Form or agreed
            by the parties in writing;
            <br />
            &#34;Lead&#34; means either an email or telephone call received by the Member from any person who has
            contacted the Member using the contact form or contact details supplied on the Website(s);
            <br />
            &#34;Lead Content&#34; means any data or information generated by or resulting from the activities of a
            Lead;
            <br />
            &#34;Logo&#34; means the Zoopla logo or any other logo as Zoopla or any Group Company may from time to time
            provide to the Member;
            <br />
            &#34;Marketing Materials&#34; means the marketing materials provided to the Member by Zoopla or any Group
            Company for the purpose of promoting the Services;
            <br />
            &#34;Member&#34; means the Agent, the Online Agent or the Developer set out in the Order Form;
            <br />
            &#34;Minimum Term&#34; any minimum order period or term (other than the Initial Term or Renewal Term) for
            Services as set out in a Services Amendment Form or on ZooplaPro;
            <br />
            &#34;Online Agent&#34; means an estate agent, lettings agent (and in Scotland, solicitor agents) and/or
            commercial property agent that operates primarily via a website (rather than a physical branch) and/or does
            not operate through a local office network;
            <br />
            &#34;Order Form&#34; means the order form for Services (as agreed, amended or added to from time to time by
            a Services Amendment Form, via ZooplaPro, via Salesforce or otherwise by the parties in writing) indicating
            the Services to be provided under the Contract together with any specific terms relating to Fees or portal
            obligations;
            <br />
            &#34;Personal Data&#34; is defined by the Data Protection Legislation;
            <br />
            &#34;Photograph Content&#34; means any Content in a photograph format;
            <br />
            &#34;Photograph Content Criteria&#34; means the Photograph Content criteria notified to the Member from time
            to time;
            <br />
            &#34;Processor&#34; is defined in the Data Protection Legislation;
            <br />
            &#34;Product Specific Terms and Conditions&#34; means additional terms and conditions that relate to
            specific Services provided by Zoopla and to which, in addition to these Member Terms and Condition, the
            Member shall be subject whilst in receipt of such Services;
            <br />
            &#34;Relevant Requirements&#34; means all applicable laws, statutes, regulations, and codes relating to
            anti-bribery and anti-corruption, including the Bribery Act 2010;
            <br />
            &#34;Renewal Term&#34; has the meaning set out in clause 7.1;
            <br />
            &#34;Services&#34; means the services to be provided by Zoopla (or its Group Companies) as set out in the
            Order Form and which may include any, or a combination, of the following:
            <br />a process facilitating the upload by the Member of property details (including images) to the
            Website(s);
            <br />
            displaying the Member&#39;s properties on the Website(s);
            <br />
            providing the Member with a listing within the agent directory on the Website(s);
            <br />
            providing Leads to the Member;
            <br />
            providing advertising services to the Member;
            <br />
            providing reports and access to reporting tools to the Member; and
            <br />
            any other services provided by Zoopla (or its Group Companies) from time to time.
            <br />
            &#34;Services Amendment Form&#34; means a services amendment form, additional products order form or
            purchase order form or any other form provided by Zoopla and signed by the Member indicating an amendment or
            addition to the type or level of Services set out in the Order Form;
            <br />
            &#34;Start Date&#34; means a start date for the Contract as may be specified in the Order Form;
            <br />
            &#34;Unique User&#34; means a uniquely identifiable visitor to the Website(s) within any calendar month;
            <br />
            &#34;Upload Systems&#34; means any system made available by Zoopla to the Member to facilitate the supply of
            Content to the Website(s);
            <br />
            &#34;Video Content&#34; means any audio-visual multimedia Content in a video format;
            <br />
            &#34;Video Content Criteria&#34; means the Video Content criteria notified to the Member from time to time;
            <br />
            &#34;Website(s)&#34; means any mobile application, the website located at www.zoopla.co.uk and any other
            website whose domain is owned or controlled or powered by Zoopla or any Group Company as Zoopla may
            determine and via which Services are provided;
            <br />
            &#34;Zoopla&#34; or &#34;the Company&#34; means Zoopla Limited, a company incorporated in England and Wales
            with Company No. 06074771 whose registered office is at The Cooperage, 5 Copper Row, London, SE1 2LH; and
            <br />
            &#34;ZooplaPro&#34; means the backend tool accessible to Members for viewing and managing their Zoopla
            membership.
            <br />
            Contract between Zoopla and the Member
            <br />
            No Contract shall subsist until:
            <br />
            unless waived by Zoopla, an Order Form completed and signed by the Member is received by Zoopla (or a Group
            Company); and
            <br />
            the later of the Start Date (if any) and Zoopla (or any Group Company) commencing provision of Services
            (whether by facilitating display of Content on the Website(s) or otherwise),
            <br />
            whereupon Zoopla and the Member shall be deemed to have entered into a legally binding Contract on the
            Member Terms and Conditions set out herein and any relevant Product Specific Terms and Conditions.
            <br />
            The Contract shall be between Zoopla and the Member and shall comprise the Order Form, these Member Terms
            and Conditions and any relevant Product Specific Terms and Conditions to which the Member is subject which,
            together, shall constitute the entire agreement between the parties to the exclusion of all previous terms
            and conditions (whether between the Member and Zoopla or the Member and another Group Company) and all other
            terms and conditions (including any which the Member purports to apply under any purchase order,
            confirmation of order or other document). Each party acknowledges that, in entering into the Contract, it
            does not rely on anything that is not set out in the Order Form, these Member Terms and Conditions and any
            relevant Product Specific Terms and Conditions.
            <br />
            In the event of any conflict between these Member Terms and Conditions and the Order Form, these Member
            Terms and Conditions shall prevail and in the event of any conflict between these Member Terms and
            Conditions and any Product Specific Terms and Conditions, these Member Terms and Conditions shall prevail
            save where they relate to a matter pertaining to Services to which any relevant Product Specific Terms and
            Conditions relate whereupon such Product Specific Terms and Conditions shall prevail.
            <br />
            All Contracts between Zoopla (or any Group Company) and a Member shall be governed by these Member Terms and
            Conditions and any relevant Product Specific Terms and Conditions and any variation thereof shall have no
            effect unless expressly agreed in writing and signed by Zoopla.
            <br />
            From time to time, Zoopla may amend these Member Terms and Conditions and any Product Specific Terms and
            Conditions and reserves the right to do so in its absolute discretion, acting reasonably, at any time. Any
            changes will be posted on the Website(s).
            <br />
            Zoopla reserves the right to reject any Order Form and/or refuse to enter into a Contract or provide any
            Services to a third party at its absolute discretion, including where it believes:
            <br />
            that party is not providing the services of an Agent, Online Agent or Developer (as determined by
            Zoopla&#39;s advertising criteria); or
            <br />
            that the quality of its Content is not or will not be of a professional standard commensurate with that of
            its Members generally.
            <br />
            Services
            <br />
            Subject to these Member Terms and Conditions and any relevant Product Specific Terms and Conditions, Zoopla
            (or any Group Company as Zoopla may determine) will provide the Member with the Services in accordance with
            the Order Form.
            <br />
            Zoopla may vary the Services from time to time at its absolute discretion and the Member shall be notified
            of any such variations where necessary. Any changes will be posted on the Website(s).
            <br />
            Content and Obligations
            <br />
            The Member warrants and represents that:
            <br />
            it is an Agent, Online Agent or Developer and that it does not act as a consumer in relation to the
            Contract;
            <br />
            any individual who has signed and/or otherwise agreed to these Member Terms (as updated from time to time)
            on its behalf has the requisite corporate authority to contract on behalf of that Member;
            <br />
            Content will comply with all applicable laws (including, but not limited to, the Equality Act 2010),
            regulations and codes of practice in the United Kingdom and any compliance guidelines published or made
            available by Zoopla from time to time, will not be defamatory, misleading, discriminatory or infringe any
            copyright, trade mark or other intellectual property rights or rights of any third party whatsoever and will
            not contain any Personal Data;
            <br />
            any Video Content will:
            <br />
            be of a good quality in Zoopla&#39;s reasonable opinion and comply with the Video Content Criteria;
            <br />
            only contain images related to the relevant property;
            <br />
            not contain telephone numbers or email addresses other than Zoopla contact details;
            <br />
            not contain any Personal Data;
            <br />
            not contain any promotion of the Member, except for its own logo; and
            <br />
            not contain any advertisements of any other products or services of the Member or any third parties, except
            for a &#39;powered by&#39; logo of the production company.
            <br />
            For the avoidance of doubt, Video Content displayed on the Member&#39;s own profile page may contain
            promotion of other services that the Member provides;
            <br />
            any Photograph Content will:
            <br />
            be of a good quality in Zoopla&#39;s reasonable opinion and comply with the Photograph Content Criteria;
            <br />
            only contain the Member&#39;s profile photograph(s) or images related to the relevant property;
            <br />
            not contain telephone numbers or email addresses other than Zoopla contact details;
            <br />
            not contain any Personal Data;
            <br />
            not contain any promotion of the Member; and
            <br />
            not contain any advertisements of any other products or services of the Member or any third parties;
            <br />
            it is responsible for the integrity of the Content which is in all respects true, complete and accurate to
            the best of the Member&#39;s knowledge and belief and the Member shall promptly update or correct Content on
            becoming aware of any errors or inaccuracies and shall provide such assistance as Zoopla shall reasonably
            require to identify and remedy any unauthorised use of Content;
            <br />
            within no more than 3 Business Days of:
            <br />a property going &#34;under offer&#34;;
            <br />a sale or leasing contract being entered into in respect of a property; or
            <br />
            the property being taken off the market,
            <br />
            the Member will either alter the status of the property details in the upload provided to Zoopla so that it
            may be displayed as &#34;under offer&#34; &#34;sold&#34; or &#34;let&#34; as appropriate on the Website(s)
            or will remove the property from the upload provided to Zoopla so that it is no longer displayed on the
            Website(s);
            <br />
            it has the authority to market the properties in the Content;
            <br />
            it holds all necessary authorities, consents and licences necessary to use, display, reproduce, publish the
            Content and has authority to and grants Zoopla (and its Group Companies) a licence of the Content on the
            terms set out in clause 3.2;
            <br />
            it has read and will abide by all notices posted on the Website(s) from time to time that are relevant to
            the provision of the Services;
            <br />
            each of its branch offices will only upload details of properties they have received instructions for
            specifically at each branch office location, and that no branch office will upload details of properties
            originating from any other branch office location;
            <br />
            it shall not use Zoopla&#39;s name, the name of any Group Company or any Logos, trade or services marks of
            Zoopla or the Group in a defamatory or derogatory manner or in any way that might bring Zoopla, the Group or
            its directors or employees into disrepute nor shall the Member misuse or deface (or allow to be misused or
            defaced) any Marketing Materials provided to it;
            <br />
            it will abide by any applicable industry code of conduct, recommendations or guidelines issued by any
            relevant trade organisation, including the National Landlords Association and the Residential Landlord&#39;s
            Association, and will abide by all applicable laws and regulations applying to or affecting Members
            including, but not limited to, Consumer Protection from Unfair Trading Regulations 2008 and the Business
            Protection from Misleading Marketing Regulations 2008;
            <br />
            it will provide a contactable telephone number and shall ensure that the majority of calls made to that
            telephone number are answered in person. Where a trackable telephone number has been allocated to the Member
            by Zoopla, the Member will use this number to enable Zoopla to effectively monitor Leads delivered to the
            Member and take no actions that would interfere with such monitoring, and the Member agrees that Zoopla and
            its suppliers may record all telephone calls for the purposes of monitoring Leads delivered or replaying
            Leads to Members; and
            <br />
            it shall ensure that only its authorised persons have access to the Services and the Upload Systems and that
            where it provides Content via the Upload Systems it shall only do so in a format compatible with any
            technical specifications issued by Zoopla from time to time. The member agrees to use this format to display
            details of the property only, as laid out, and not to use these areas to advertise ancillary company
            information.
            <br />
            The Member grants Zoopla and the Group a non-exclusive, royalty free, perpetual licence to copy, reproduce,
            display, sell, publish, adapt and otherwise use the Content or data or other information derived therefrom
            for any purpose whatsoever (including entering into agreements with third parties for the provision of the
            Content or data derived therefrom). This licence shall survive termination of the Contract, but (for the
            avoidance of doubt) shall have no effect on the Member&#39;s rights (or its licensor&#39;s rights, as
            applicable) in respect of such Content or data, save to the extent specified herein. The Member agrees that
            Zoopla and any Group Company may, but shall not be required to, identify the Member as the source of the
            Content on the Website(s) or in any other medium through which the Content or any derivative thereof is
            published or displayed.
            <br />
            Zoopla:
            <br />
            may in its absolute discretion, at any time, remove, cause to be removed or decline to display any Content
            on the Website(s) which fails to comply with the terms of this Contract, and shall notify the Member of such
            decision either prior to, or at the time of, the relevant Content being removed or rejected;
            <br />
            may without prejudice to Zoopla&#39;s right as set out in clause 3.3(a) above, require the Content to be
            amended at any time if Zoopla considers or has reason to believe that the Member is in breach of the
            Contract or any applicable law or regulation or where it deems in its absolute discretion the Content to be
            of poor quality in terms of presentation, information provided or otherwise; and
            <br />
            reserves the right to charge the Member for additional fees or in a manner it deems appropriate or on a per
            property basis if Zoopla has reason to believe that Content uploaded by any of the Member&#39;s branch
            offices is in breach of clause 3.1(k) above.
            <br />
            The Member acknowledges and agrees that:
            <br />
            it will continue to be bound by these Member Terms irrespective of whether:
            <br />
            the individual who has signed and/or agreed to the Member Terms on its behalf subsequently ceases to be
            employed or otherwise engaged by the Member or subsequently ceases to be authorised to act on behalf of the
            Member; or
            <br />
            the whole or substantially whole of the Member&#39;s assets are sold or transferred to a different legal
            entity;
            <br />
            neither Zoopla nor any Group Company shall be under any obligation to monitor or censor the Content that
            appears on the Website(s) but Zoopla reserves the right for itself (and the Group) to do so;
            <br />
            neither Zoopla nor any Group Company is responsible for any error or omissions in any Content;
            <br />
            as part of the Services the Member may be provided with access to data including that derived from the
            content and data provided by Zoopla&#39;s Members and other third parties. Zoopla takes reasonable care to
            ensure that such data is accurate and up to date but makes no representation or warranty about the accuracy
            or completeness of such data and the data is not intended to be, and must not be treated by a Member as,
            comprehensive but an aggregation of the content and data available to Zoopla at the time of provision and
            available to the Member in accordance with its level of membership;
            <br />
            technological failure may impede the provision of the Services or prevent access to all or any part of the
            Content displayed on the Website(s) or to the Upload Systems. Zoopla makes no representation or warranty
            that the Website(s), the Services, the Content or the Upload Systems will be accessible or available at all
            times, or that the whole or any part of the Website(s), Services, the Content or Upload Systems will be free
            from error and while Zoopla will make reasonable endeavours to notify the Member in advance, it may suspend
            temporarily or alter the operation of the Website(s), Services or the Upload System without notice to the
            Member;
            <br />
            it is responsible for and will pay all telecommunications and internet access charges incurred by it when
            using the Website(s);
            <br />
            transmission of data over the internet can be subject to delays and errors and can cause corruption of data
            for which neither Zoopla nor any Group Company shall be responsible;
            <br />
            from time to time Zoopla shall be entitled to increase the fees payable by the Member in the event that,
            following an assessment by Zoopla, it is determined by Zoopla that the number of properties displayed on the
            Website on behalf of the Member has increased such that the number of properties exceeds the average for
            Members of a similar type. In assessing the number of properties and the applicable average for these
            purposes:
            <br />
            an Agent&#39;s properties (and those of other Agents) shall be assessed on a per-branch basis by reference
            to an appropriate geographical area;
            <br />a Developer&#39;s properties (and those of other Developers) shall be assessed on a per-Development
            basis;
            <br />
            an Online Agent&#39;s properties (and those of other Online Agents) shall be assessed by reference to
            appropriate geographical areas;
            <br />
            and in any event an assessment will be made by reference to any relevant guidelines issued by Zoopla from
            time to time. Any increase in fees will be calculated on either a per-property or per-Development basis so
            as to fairly reflect the increase in the volume of the Member&#39;s displayed properties;
            <br />
            Zoopla may limit the number of photographs that may be displayed by the Member to 20 images per property;
            <br />
            in providing the Services, and in order to provide information about other products and services, Zoopla and
            the Group Companies may, unless otherwise agreed in writing by Zoopla and the Member, contact the Member by
            post, telephone, electronic means, including e-mail and other electronic media and the Member shall maintain
            a valid working e-mail address for each of its branch offices, head offices, regional offices and
            development offices and shall immediately notify the Company of any change of e-mail addresses;
            <br />
            it shall for the duration of the Contract, take reasonable steps to promote the Website(s) to its customers
            and display any Marketing Materials provided by Zoopla at its premises, provide a link on its website to the
            Website(s) and include the Logo in its sales and advertising materials. For the purpose of carrying out
            these obligations only, Zoopla grants the Member a non-exclusive licence for the duration of the Contract to
            use, display and copy the Logo, Zoopla name and any trade or services marks used by Zoopla or the Group and
            copyright (or other intellectual property rights) contained in the Marketing Material; and
            <br />
            all intellectual property rights in the Services, technology supporting the Services (including the Upload
            System) and the Website(s) vest in Zoopla and/or its licensors/sub-contractors and that the Member has no
            rights in, or to, such intellectual property other than the right to use the same in accordance with the
            Contract. For the avoidance of doubt, save to the extent otherwise specified in the Contract, all
            intellectual property rights in the Content shall remain vested in the Member (or its licensors, as
            applicable).
            <br />
            Any third party, purporting to act as agent for or on behalf of a prospective Member, contracting with
            Zoopla for the provision for Services warrants and represents that it has the full and valid authority of
            that prospective Member to bind it and to the extent that:
            <br />
            that third party exceeds its authority; and/or
            <br />
            the prospective Member refuses to such pay any Fees or charges,
            <br />
            that third party shall be liable, on an indemnity basis, for all Fees and any other charges due hereunder.
            <br />
            The Member shall not publish, disclose, reproduce or create any derivative works from any information
            obtained pursuant to the Member&#39;s use of the Services unless expressly agreed in writing by Zoopla.
            <br />
            The Member shall promptly notify Zoopla if there is any increase or decrease in the number of branch offices
            operated by the Member.
            <br />
            The Member shall promptly notify Zoopla in writing in the event:
            <br />
            there are no longer any properties left for sale or rent in a Development; or
            <br />
            it decides that a Development should no longer be listed for any reason.
          </p>
          <a href="javascript:history.back()">
            <div className="group-1-3">
              <div className="overlap-group1-6" style={{ backgroundImage: `url(${overlapGroup1})` }}>
                <img className="line-31-7" src={line31} alt="Line 31" />
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  );
}

export default MacBookAir8;
